development:
  twitter:
    api_key: <%= ENV['DEV_TWITTER_API_KEY'] %>
    secret_key: <%= ENV['DEV_TWITTER_SECRET_KEY'] %>
    access_token: <%= ENV['DEV_TWITTER_ACCESS_TOKEN'] %>
    secret_token: <%= ENV['DEV_TWITTER_SECRET_TOKEN'] %>
test:
  twitter:
    api_key: <%= ENV['TEST_TWITTER_API_KEY'] %>
    secret_key: <%= ENV['TEST_TWITTER_SECRET_KEY'] %>
    access_token: <%= ENV['TEST_TWITTER_ACCESS_TOKEN'] %>
    secret_token: <%= ENV['TEST_TWITTER_SECRET_TOKEN'] %>
production:
  twitter:
    api_key: <%= ENV['TWITTER_API_KEY'] %>
    secret_key: <%= ENV['TWITTER_SECRET_KEY'] %>
    access_token: <%= ENV['TWITTER_ACCESS_TOKEN'] %>
    secret_token: <%= ENV['TWITTER_SECRET_TOKEN'] %>
